name: pull-request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Scan with Ermetic GitHub action
#        uses: ermetic/code-scan-action@b5987271f52b39677a58c52e5e8bad4f8c0a0e2f
        uses: ermetic/actions@a1c91e7e49676aa72a2f7a10bee1d6c0b3d2e44b
        with:
          api-token: ${{ secrets.ERMETIC_API_TOKEN }}
          api-url: https://us12.dev.app.ermetic.com
        
