name: pull-request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Scan with Ermetic GitHub action
#        uses: uses: ermetic/actions/iac/scan@v1
        uses: ermetic/actions@a1c91e7e49676aa72a2f7a10bee1d6c0b3d2e44b
        with:
          api-token: ${{ secrets.ERMETIC_API_TOKEN }}
          api-url: https://us13.dev.app.ermetic.com
        
