name: push

on:
  push:
    branches:
      - main
      - 'dudunahum/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Scan with Ermetic GitHub action
        uses: ermetic/actions/iac/scan
        with:
          api-token: ${{ secrets.ERMETIC_API_TOKEN }}
          api-url: https://us12.dev.app.ermetic.com
        
