name: push

on:
  push:
    branches:
      - main
      - 'dudunahum/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Scan with Ermetic GitHub action
        uses: ermetic/actions/iac/scan@v1
        with:
          api-token: OTcyMDA5NzItMDk3Mi0wOTcyLTA5NzItOTcyOTcyOTcyOTcyLmYzMWEyOGQxLTliYzUtNDYzMS1hYmNkLTY2NDZjMTM4NzE5Yy5QMG4vOFdoMmVBdG9xSzNCVHRoaGJLK2hLc1V0ajEyYw==
          api-url: https://us13.dev.app.ermetic.com
          paths: ./
          exclude-paths: ./terraform/aws/
          fail-on-min-severity: critical
          output-file-formats: csv,json,junit,sarif
          output-file-name: dudu_results
          logs: true
