name: push

on:
  push:
    branches:
      - main
      - Branch1
      - Branch**
      - branch**
      - 'dudunahum/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Scan with Ermetic GitHub action
        uses: ermetic/actions/iac/scan@v1
        with:
          api-token: OTcyMDA5NzItMDk3Mi0wOTcyLTA5NzItOTcyOTcyOTcyOTcyLmYzMWEyOGQxLTliYzUtNDYzMS1hYmNkLTY2NDZjMTM4NzE5Yy5QMG4vOFdoMmVBdG9xSzNCVHRoaGJLK2hLc1V0ajEyYw==
          api-url: https://us13.dev.app.ermetic.com
          paths: ./
          policies: 6726dcc0-5ff5-459d-b473-a780bef7665c
          fail-on-min-severity: critical
          output-file-formats: csv,json,junit,sarif
          output-file-name: dudu_results
          silent: false
          logs: true
          types: terraform
